// <auto-generated />
namespace SailorWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddStatusToBlogCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStatusToBlogCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202104211940018_AddStatusToBlogCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
